os: osx
osx_image: xcode12
language: swift
script: 
  - xcodebuild clean build test -project EssentialFeed.xcodeproj  -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
  - xcodebuild clean build test -workspace EssentialApp.xcworkspace  -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=YES ONLY_ACTIVE_ARCH=YES

